create table public.test_parcels (
  id bigint not null,
  block integer not null,
  lot integer not null,
  ext integer not null default 0,
  created_at timestamp without time zone null default '2020-01-01 00:00:00'::timestamp without time zone,
  retired_at timestamp without time zone null,
  constraint test_parcels_pkey primary key (id),
  constraint test_parcels_block_lot_ext_key unique (block, lot, ext)
) TABLESPACE pg_default;

create table public.test_parcel_addresses (
  parcel_id bigint not null,
  place_id text not null,
  effective_date date not null default now(),
  end_date date null,
  constraint test_parcel_addresses_parcel_id_fkey foreign KEY (parcel_id) references test_parcels (id) on delete CASCADE,
  constraint test_parcel_addresses_place_id_fkey foreign KEY (place_id) references test_geocoded_addresses (place_id) on delete CASCADE
) TABLESPACE pg_default;


create table public.test_geocoded_addresses (
  place_id text not null,
  devnet_address text null,
  sourcename text null,
  attribution text null,
  license text null,
  attribution_url text null,
  match_type text null,
  country text null,
  country_code text null,
  state text null,
  city text null,
  postcode text null,
  district text null,
  street text null,
  housenumber text null,
  iso3166_2 text null,
  result_type text null,
  formatted text null,
  address_line1 text null,
  address_line2 text null,
  plus_code text null,
  plus_code_short text null,
  lat double precision null,
  lon double precision null,
  timezone text null,
  timezone_offset text null,
  timezone_abbreviation text null,
  geocode_id text null,
  category text null,
  county text null,
  distance double precision null,
  footway text null,
  hamlet text null,
  name text null,
  old_name text null,
  ref text null,
  state_code text null,
  suburb text null,
  town text null,
  village text null,
  fts_address_line1 tsvector GENERATED ALWAYS as (
    to_tsvector(
      'english'::regconfig,
      COALESCE(address_line1, ''::text)
    )
  ) STORED null,
  constraint test_geocoded_addresses_pkey primary key (place_id)
) TABLESPACE pg_default;


create table public.field_review_notes (
  id bigserial not null,
  review_id bigint not null,
  note text not null,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid (),
  constraint field_review_notes_pkey primary key (id),
  constraint field_review_notes_created_by_fkey foreign KEY (created_by) references employees (user_id) on update CASCADE,
  constraint field_review_notes_review_id_fkey foreign KEY (review_id) references field_reviews (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.field_review_status_history (
  id bigserial not null,
  review_id bigint not null,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid (),
  status_id bigint null,
  description text null,
  constraint field_review_statuses_pkey primary key (id),
  constraint field_review_status_history_status_id_fkey foreign KEY (status_id) references field_review_statuses (id),
  constraint field_review_statuses_review_id_fkey foreign KEY (review_id) references field_reviews (id) on delete CASCADE,
  constraint fk_field_review_statuses_user foreign KEY (created_by) references auth.users (id)
) TABLESPACE pg_default;

create table public.field_review_statuses (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  constraint field_review_statuses_pkey1 primary key (id)
) TABLESPACE pg_default;

create table public.field_review_types (
  id bigserial not null,
  slug text not null,
  display_name text not null,
  description text null,
  active boolean not null default true,
  default_due_days integer null,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid (),
  constraint field_review_types_pkey primary key (id),
  constraint field_review_types_slug_uniq unique (slug),
  constraint field_review_types_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint field_review_types_slug_lower_chk check ((slug = lower(slug)))
) TABLESPACE pg_default;

create table public.field_reviews (
  id bigserial not null,
  parcel_id bigint not null,
  due_date date null,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid (),
  site_visited_at timestamp without time zone null,
  type_id bigint null,
  constraint field_reviews_pkey primary key (id),
  constraint field_reviews_parcel_id_fkey foreign KEY (parcel_id) references test_parcels (id) on delete CASCADE,
  constraint field_reviews_type_id_fkey foreign KEY (type_id) references field_review_types (id),
  constraint fk_field_reviews_user foreign KEY (created_by) references auth.users (id)
) TABLESPACE pg_default;

create table public.neighborhoods (
  neighborhood integer generated by default as identity not null,
  "group" integer null,
  polygon jsonb[] null,
  set_id bigint null,
  name text null,
  id bigserial not null,
  constraint neighborhoods_pkey primary key (id),
  constraint neighborhoods_id_key unique (id),
  constraint neighborhoods_set_id_fkey foreign KEY (set_id) references neighborhood_sets (id)
) TABLESPACE pg_default;

create table public.neighborhood_sets (
  id bigserial not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  retired_at timestamp with time zone null,
  created_by uuid not null default auth.uid (),
  constraint neighborhood_sets_pkey primary key (id)
) TABLESPACE pg_default;

create table public.test_parcel_neighborhoods (
  id bigserial not null,
  parcel_id bigint not null,
  neighborhood_id integer not null,
  effective_date date not null,
  end_date date null,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid (),
  constraint test_parcel_neighborhoods_pkey primary key (id),
  constraint test_parcel_neighborhoods_neighborhood_id_fkey foreign KEY (neighborhood_id) references neighborhoods (id) on delete CASCADE,
  constraint test_parcel_neighborhoods_parcel_id_fkey foreign KEY (parcel_id) references test_parcels (id) on delete CASCADE,
  constraint test_parcel_neighborhoods_date_chk check (
    (
      (end_date is null)
      or (end_date > effective_date)
    )
  )
) TABLESPACE pg_default;