CREATE TABLE
  IF NOT EXISTS public.files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket text NULL,
    path text NULL,
    filename text NULL,
    mime_type text NULL,
    size_bytes bigint NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NULL
  );

/* ----------------------------
Parcels
---------------------------- */
CREATE TABLE
  IF NOT EXISTS public.parcels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block integer NULL,
    lot integer NULL,
    ext integer NULL,
    parcel_number text NULL, -- optional human-friendly id
    created_at timestamptz NOT NULL DEFAULT now (),
    retired_at timestamptz NULL
  );

CREATE INDEX IF NOT EXISTS parcels_block_lot_ext_idx ON public.parcels (block, lot, ext);

/* ============================================================
REVIEWS (BASE + TYPE HEADERS)
============================================================ */
CREATE TABLE
  IF NOT EXISTS public.reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind public.review_kind NOT NULL,
    title text NULL,
    due_date date NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid (),
    closed_at timestamptz NULL,
    closed_by uuid NULL
  );

CREATE INDEX IF NOT EXISTS reviews_kind_created_at_idx ON public.reviews (kind, created_at DESC);

CREATE INDEX IF NOT EXISTS reviews_due_date_idx ON public.reviews (due_date)
WHERE
  due_date IS NOT NULL;

-- ----- NOTES
CREATE TABLE
  IF NOT EXISTS public.review_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
    note text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE INDEX IF NOT EXISTS review_notes_idx ON public.review_notes (review_id, created_at DESC);

-- ----- FILE LINKS
CREATE TABLE
  IF NOT EXISTS public.review_files (
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
    file_id bigint NOT NULL REFERENCES public.files (id) ON DELETE RESTRICT,
    caption text NULL,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid (),
    PRIMARY KEY (review_id, file_id)
  );

-- ----- ASSIGNMENTS (daterange)
CREATE TABLE
  IF NOT EXISTS public.review_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
    employee_id bigint NOT NULL REFERENCES public.employees (id),
    valid daterange NOT NULL,
    assigned_by uuid NOT NULL DEFAULT auth.uid (),
    created_at timestamptz NOT NULL DEFAULT now ()
  );

CREATE TABLE
  IF NOT EXISTS public.parcel_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id bigint NOT NULL REFERENCES public.parcels (id) ON DELETE CASCADE,
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE
  );

/* ----------------------------
Structures
---------------------------- */
CREATE TABLE
  IF NOT EXISTS public.structure_uses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL, -- e.g., 'Single Family', 'Multi-Family', 'Commercial', 'Industrial', 'Agricultural' 'Office', etc.
    description text NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.structures (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NULL REFERENCES public.reviews (id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    retired_at timestamptz NULL
  );

CREATE TABLE
  IF NOT EXISTS public.structure_parcel_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id bigint NOT NULL REFERENCES public.structures (id) ON DELETE CASCADE,
    parcel_id bigint NOT NULL REFERENCES public.parcels (id) ON DELETE CASCADE,
    review_id bigint NULL REFERENCES public.reviews (id) ON DELETE SET NULL,
    effective_at date NOT NULL DEFAULT current_date,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.structure_conditions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL, -- e.g., 'Excellent', 'Very Good', 'Good', 'Fair', 'Poor', 'Unsound'
    description text NULL,
    sort_order int NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.structure_condition_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NULL REFERENCES public.reviews (id) ON DELETE SET NULL,
    structure_id bigint NOT NULL REFERENCES public.structureS (id) ON DELETE CASCADE,
    condition_id bigint NOT NULL REFERENCES public.structure_conditions (id) ON DELETE RESTRICT,
    effective_at date NOT NULL DEFAULT current_date,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS structure_section_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL, -- e.g., 'Basement, Main Floor, Floor, Attic, Garage
    description text NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.structure_section_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NULL REFERENCES public.reviews (id) ON DELETE SET NULL,
    structure_id bigint NOT NULL REFERENCES public.structures (id) ON DELETE CASCADE,
    section_type bigint NOT NULL REFERENCES public.structure_section_types (id) ON DELETE RESTRICT,
    area_sqft integer NOT NULL,
    living_area_sqft integer NOT NULL,
    details jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid (),
    effective_at date NOT NULL DEFAULT current_date
  );

-- Structure snapshots contain summaries of structure components.
CREATE TABLE
  IF NOT EXISTS public.structure_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id bigint NOT NULL REFERENCES public.structures (id) ON DELETE CASCADE,
    review_id bigint NULL REFERENCES public.reviews (id) ON DELETE SET NULL,
    best_use_id bigint NULL REFERENCES public.structure_uses (id) ON DELETE SET NULL,
    condition_id bigint NULL REFERENCES public.structure_conditions (id) ON DELETE SET NULL,
    created_by uuid NOT NULL DEFAULT auth.uid (),
    created_at timestamptz NOT NULL DEFAULT now (),
    effective_at date NOT NULL DEFAULT current_date,
    total_area_sqft integer NULL,
    total_livable_sqft integer NULL,
    number_of_units integer NULL,
    number_of_bedrooms integer NULL,
    number_of_bathrooms numeric NULL,
    number_of_stories integer NULL,
    brick_sqft integer NULL,
    frame_sqft integer NULL,
    concrete_sqft integer NULL,
    attached_garage_sqft integer NULL,
    attic_livable_sqft integer NULL,
    attic_unfinished_sqft integer NULL,
    basement_finished_sqft integer NULL,
    basement_unfinished_sqft integer NULL,
    replacement_cost_new numeric NULL,
    sections_detail jsonb NOT NULL DEFAULT '{}'
  );

/* ----------------------------
Lands (land components / land records)
---------------------------- */
CREATE TABLE
  IF NOT EXISTS public.land_uses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL, -- e.g., 'Residential', 'Commercial', 'Agricultural', 'Industrial', 'Vacant', etc.
    description text NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.lands (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NULL REFERENCES public.reviews (id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    retired_at timestamptz NULL
  );

CREATE TABLE
  IF NOT EXISTS public.review_lands (
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
    land_id bigint NOT NULL REFERENCES public.lands (id) ON DELETE CASCADE,
    PRIMARY KEY (review_id, land_id)
  );

CREATE TABLE
  IF NOT EXISTS public.land_parcel_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    land_id bigint NOT NULL REFERENCES public.lands (id) ON DELETE CASCADE,
    parcel_id bigint NOT NULL REFERENCES public.parcels (id) ON DELETE CASCADE,
    review_id bigint NULL REFERENCES public.reviews (id) ON DELETE SET NULL,
    effective_at date NOT NULL DEFAULT current_date,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.land_use_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NULL REFERENCES public.reviews (id) ON DELETE SET NULL,
    land_id bigint NOT NULL REFERENCES public.lands (id) ON DELETE CASCADE,
    land_use_id bigint NOT NULL REFERENCES public.land_uses (id) ON DELETE RESTRICT,
    effective_at date NOT NULL DEFAULT current_date,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

-- land versions
CREATE TABLE
  IF NOT EXISTS public.land_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    land_id bigint NOT NULL REFERENCES public.lands (id) ON DELETE CASCADE,
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE RESTRICT,
    area_sqft integer NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid (),
    effective_at date NOT NULL DEFAULT current_date,
    data jsonb NOT NULL
  );

CREATE TABLE
  IF NOT EXISTS public.land_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    land_id bigint NOT NULL REFERENCES public.lands (id) ON DELETE CASCADE,
    review_id bigint NULL REFERENCES public.reviews (id) ON DELETE SET NULL,
    created_by uuid NOT NULL DEFAULT auth.uid (),
    created_at timestamptz NOT NULL DEFAULT now (),
    effective_at date NOT NULL DEFAULT current_date,
    land_use_id bigint NULL REFERENCES public.land_uses (id) ON DELETE SET NULL,
    area_sqft integer NULL,
    frontage_ft integer NULL,
    depth_ft integer NULL,
    shape_detail jsonb NOT NULL DEFAULT '{}'
  );

/* ============================================================
APPEALS (CASE + REVIEW WORKFLOW)
============================================================ */
CREATE TABLE
  IF NOT EXISTS public.parcel_value_sets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id bigint NOT NULL REFERENCES public.parcels (id) ON DELETE CASCADE,
    tax_year int NOT NULL,
    approach text NOT NULL, -- 'cost','sales_model','income','appeal','manual'
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE RESTRICT,
    totals jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now (),
    supersedes_value_set_id bigint NULL REFERENCES public.parcel_value_sets (id)
  );

CREATE TABLE
  IF NOT EXISTS public.appeals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_value_set_id bigint NULL REFERENCES public.parcel_value_sets (id) ON DELETE SET NULL,
    level text NOT NULL, -- 'informal','boe','stc','court'
    filed_at date NOT NULL DEFAULT current_date,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.appeal_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
    appeal_id bigint NOT NULL REFERENCES public.appeals (id) ON DELETE CASCADE
  );

CREATE TABLE
  IF NOT EXISTS public.appeal_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appeal_id bigint NOT NULL REFERENCES public.appeals (id) ON DELETE CASCADE,
    decided_at date NOT NULL,
    decision_type text NOT NULL, -- 'upheld','reduced','increased','dismissed','withdrawn'
    decision_review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE RESTRICT,
    result_value_set_id bigint NULL REFERENCES public.parcel_value_sets (id) ON DELETE SET NULL
  );

CREATE TABLE
  IF NOT EXISTS public.appeal_hearings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appeal_id bigint NOT NULL REFERENCES public.appeals (id) ON DELETE CASCADE,
    hearing_date date NOT NULL,
    hearing_review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE RESTRICT,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE INDEX IF NOT EXISTS appeal_decisions_appeal_idx ON public.appeal_decisions (appeal_id, decided_at DESC);

CREATE TABLE
  IF NOT EXISTS public.parcel_value_set_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value_set_id bigint NOT NULL REFERENCES public.parcel_value_sets (id) ON DELETE CASCADE,
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE RESTRICT,
    residential_land_value numeric NULL,
    commercial_land_value numeric NULL,
    agricultural_land_value numeric NULL,
    total_land_value numeric NOT NULL,
    residential_improvement_value numeric NULL,
    commercial_improvement_value numeric NULL,
    agricultural_improvement_value numeric NULL,
    total_improvement_value numeric NOT NULL,
    total_value numeric NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    effective_at date NOT NULL DEFAULT current_date
  );

/* ============================================================
Sales Base + Review
============================================================ */
create table
  if not exists public.sale_types (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null, -- e.g., 'Arms-Length', 'Foreclosure', 'Short Sale', etc.
    description text null,
    created_at timestamptz not null default now (),
    created_by uuid not null default auth.uid ()
  );

create table
  if not exists public.sales (
    id bigint generated by default as identity primary key,
    review_id bigint not null references public.reviews (id) on delete cascade,
    created_at timestamptz not null default now (),
    created_by uuid not null default auth.uid ()
  );

-- Enforce 1:1 between a "sale creation review" and the sale record (recommended)
create unique index if not exists sales_review_id_uniq on public.sales (review_id);

create table
  if not exists public.sale_reviews (
    id bigint generated by default as identity primary key,
    review_id bigint references public.reviews (id) on delete cascade,
    sale_id bigint not null references public.sales (id) on delete cascade,
    created_at timestamptz not null default now (),
    created_by uuid not null default auth.uid ()
  );

create table
  if not exists public.sales_versions (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references public.sales (id) on delete cascade,
    review_id bigint not null references public.reviews (id) on delete restrict,
    sale_date date not null,
    sale_price numeric not null,
    sale_type_id bigint null references public.sale_types (id) on delete set null,
    grantor text null,
    grantee text null,
    -- Anything extra you don't want as columns
    property_details jsonb not null default '{}',
    -- Audit
    created_at timestamptz not null default now (),
    created_by uuid not null default auth.uid (),
    -- As-of
    effective_at date not null default current_date
  );

create table
  if not exists public.sale_parcels (
    id bigint generated by default as identity primary key,
    sale_version_id bigint not null references public.sales_versions (id) on delete cascade,
    parcel_id bigint not null references public.parcels (id) on delete cascade,
    created_at timestamptz not null default now (),
    created_by uuid not null default auth.uid ()
  );

/* ============================================================
Permits Base + Review
============================================================ */
CREATE TABLE
  IF NOT EXISTS public.permits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.permit_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id bigint REFERENCES public.reviews (id) ON DELETE CASCADE,
    permit_id bigint NOT NULL REFERENCES public.permits (id) ON DELETE CASCADE,
    payload jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.permits_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permit_id bigint NOT NULL REFERENCES public.permits (id) ON DELETE CASCADE,
    review_id bigint NOT NULL REFERENCES public.reviews (id) ON DELETE RESTRICT,
    permit_number text NOT NULL,
    issue_date date NOT NULL,
    permit_type text NOT NULL,
    description text NULL,
    property_details jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid (),
    effective_at date NOT NULL DEFAULT current_date
  );

/* ============================================================
PER-TYPE STATUS TRACKING
============================================================ */
-- ----- STATUS CATALOGS
CREATE TABLE
  IF NOT EXISTS public.sale_review_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    is_terminal boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now ()
  );

CREATE TABLE
  IF NOT EXISTS public.permit_review_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    is_terminal boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now ()
  );

CREATE TABLE
  IF NOT EXISTS public.parcel_review_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    is_terminal boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now ()
  );

CREATE TABLE
  IF NOT EXISTS public.appeal_review_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    is_terminal boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now ()
  );

-- ----- STATUS HISTORY
CREATE TABLE
  IF NOT EXISTS public.sale_review_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_review_id bigint NOT NULL REFERENCES public.sale_reviews (id) ON DELETE CASCADE,
    status_id bigint NOT NULL REFERENCES public.sale_review_statuses (id),
    note text NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE INDEX IF NOT EXISTS sale_review_status_hist_idx ON public.sale_review_status_history (sale_review_id, created_at DESC);

CREATE TABLE
  IF NOT EXISTS public.permit_review_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permit_review_id bigint NOT NULL REFERENCES public.permit_reviews (id) ON DELETE CASCADE,
    status_id bigint NOT NULL REFERENCES public.permit_review_statuses (id),
    note text NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE INDEX IF NOT EXISTS permit_review_status_hist_idx ON public.permit_review_status_history (permit_review_id, created_at DESC);

CREATE TABLE
  IF NOT EXISTS public.parcel_review_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_review_id bigint NOT NULL REFERENCES public.parcel_reviews (id) ON DELETE CASCADE,
    status_id bigint NOT NULL REFERENCES public.parcel_review_statuses (id),
    note text NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE TABLE
  IF NOT EXISTS public.appeal_review_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appeal_review_id bigint NOT NULL REFERENCES public.appeal_reviews (id) ON DELETE CASCADE,
    status_id bigint NOT NULL REFERENCES public.appeal_review_statuses (id),
    note text NULL,
    created_at timestamptz NOT NULL DEFAULT now (),
    created_by uuid NOT NULL DEFAULT auth.uid ()
  );

CREATE INDEX IF NOT EXISTS appeal_review_status_hist_idx ON public.appeal_review_status_history (appeal_review_id, created_at DESC);

/* ============================================================
WORKFLOW FUNCTIONS
============================================================ */