create table
    public.reviews (
        id bigint generated by default as identity not null,
        kind public.review_kind not null,
        title text null,
        due_date date null,
        created_at timestamp
        with
            time zone not null default now (),
            created_by uuid not null default auth.uid (),
            closed_at timestamp
        with
            time zone null,
            closed_by uuid null,
            constraint reviews_pkey primary key (id)
    ) TABLESPACE pg_default;

create table
    public.sale_reviews (
        id bigint generated by default as identity not null,
        review_id bigint null,
        sale_id bigint not null,
        created_at timestamp
        with
            time zone not null default now (),
            created_by uuid not null default auth.uid (),
            constraint sale_reviews_pkey primary key (id),
            constraint sale_reviews_review_id_fkey foreign KEY (review_id) references reviews (id) on delete CASCADE,
            constraint sale_reviews_sale_id_fkey foreign KEY (sale_id) references sales (id) on delete CASCADE
    ) TABLESPACE pg_default;

create table
    public.sale_review_statuses (
        id bigint generated by default as identity not null,
        slug text not null,
        name text not null,
        is_terminal boolean not null default false,
        created_at timestamp
        with
            time zone not null default now (),
            constraint sale_review_statuses_pkey primary key (id),
            constraint sale_review_statuses_slug_key unique (slug)
    ) TABLESPACE pg_default;

create table
    public.sale_review_status_history (
        id bigint generated by default as identity not null,
        sale_review_id bigint not null,
        status_id bigint not null,
        note text null,
        created_at timestamp
        with
            time zone not null default now (),
            created_by uuid not null default auth.uid (),
            constraint sale_review_status_history_pkey primary key (id),
            constraint sale_review_status_history_sale_review_id_fkey foreign KEY (sale_review_id) references sale_reviews (id) on delete CASCADE,
            constraint sale_review_status_history_status_id_fkey foreign KEY (status_id) references sale_review_statuses (id)
    ) TABLESPACE pg_default;

create table
    public.review_notes (
        id bigint generated by default as identity not null,
        review_id bigint not null,
        note text not null,
        created_at timestamp
        with
            time zone not null default now (),
            created_by uuid not null default auth.uid (),
            constraint review_notes_pkey primary key (id),
            constraint review_notes_review_id_fkey foreign KEY (review_id) references reviews (id) on delete CASCADE
    ) TABLESPACE pg_default;

create table
    public.review_assignments (
        id bigint generated by default as identity not null,
        review_id bigint not null,
        employee_id bigint not null,
        valid daterange not null,
        assigned_by uuid not null default auth.uid (),
        created_at timestamp
        with
            time zone not null default now (),
            constraint review_assignments_pkey primary key (id),
            constraint review_assignments_employee_id_fkey foreign KEY (employee_id) references employees (id),
            constraint review_assignments_review_id_fkey foreign KEY (review_id) references reviews (id) on delete CASCADE
    ) TABLESPACE pg_default;

create table
    public.parcel_reviews (
        id bigint generated by default as identity not null,
        parcel_id bigint not null,
        review_id bigint not null,
        constraint parcel_reviews_pkey primary key (id),
        constraint parcel_reviews_review_id_fkey foreign KEY (review_id) references reviews (id) on delete CASCADE
    ) TABLESPACE pg_default;

create table
    public.parcel_review_statuses (
        id bigint generated by default as identity not null,
        slug text not null,
        name text not null,
        is_terminal boolean not null default false,
        created_at timestamp
        with
            time zone not null default now (),
            constraint parcel_review_statuses_pkey primary key (id),
            constraint parcel_review_statuses_slug_key unique (slug)
    ) TABLESPACE pg_default;

create table
    public.parcel_review_status_history (
        id bigint generated by default as identity not null,
        parcel_review_id bigint not null,
        status_id bigint not null,
        note text null,
        created_at timestamp
        with
            time zone not null default now (),
            created_by uuid not null default auth.uid (),
            constraint parcel_review_status_history_pkey primary key (id),
            constraint parcel_review_status_history_parcel_review_id_fkey foreign KEY (parcel_review_id) references parcel_reviews (id) on delete CASCADE,
            constraint parcel_review_status_history_status_id_fkey foreign KEY (status_id) references parcel_review_statuses (id)
    ) TABLESPACE pg_default;