create table
    public.sales (
        id bigint generated by default as identity not null,
        created_at timestamp
        with
            time zone not null default now (),
            created_by uuid not null default auth.uid (),
            constraint sales_pkey primary key (id)
    ) TABLESPACE pg_default;

create table
    public.sales_versions (
        id bigint generated by default as identity not null,
        sale_id bigint not null,
        review_id bigint not null,
        sale_date date null,
        sale_price numeric not null,
        sale_type_id bigint null,
        grantor text null,
        grantee text null,
        created_at timestamp
        with
            time zone not null default now (),
            created_by uuid not null default auth.uid (),
            effective_at date not null default CURRENT_DATE,
            constraint sales_versions_pkey primary key (id),
            constraint sales_versions_review_id_fkey foreign KEY (review_id) references reviews (id) on delete RESTRICT,
            constraint sales_versions_sale_id_fkey foreign KEY (sale_id) references sales (id) on delete CASCADE,
            constraint sales_versions_sale_type_id_fkey foreign KEY (sale_type_id) references sale_types (id) on delete set null
    ) TABLESPACE pg_default;

create table
    public.sale_parcels (
        id bigint generated by default as identity not null,
        sale_version_id bigint not null,
        parcel_id bigint not null,
        created_at timestamp
        with
            time zone not null default now (),
            created_by uuid not null default auth.uid (),
            constraint sale_parcels_pkey primary key (id),
            constraint sale_parcels_parcel_id_fkey foreign KEY (parcel_id) references parcels (id) on delete CASCADE,
            constraint sale_parcels_sale_version_id_fkey foreign KEY (sale_version_id) references sales_versions (id) on delete CASCADE
    ) TABLESPACE pg_default;