create table public.parcels (
  id bigint generated by default as identity not null,
  block integer null,
  lot integer null,
  ext integer null,
  created_at timestamp with time zone not null default now(),
  retired_at timestamp with time zone null,
  constraint parcels_pkey primary key (id)
) TABLESPACE pg_default;


create table public.addresses (
  id bigserial not null,
  place_id text not null,
  line1 text not null,
  line2 text null,
  city text not null,
  state text not null,
  postcode text not null,
  formatted text null,
  created_at timestamp with time zone not null default now(),
  created_by uuid null default auth.uid (),
  devnet_address text null,
  sourcename text null,
  attribution text null,
  license text null,
  attribution_url text null,
  match_type text null,
  country text null,
  country_code text null,
  district text null,
  street text null,
  housenumber text null,
  iso3166_2 text null,
  result_type text null,
  address_line1 text null,
  address_line2 text null,
  plus_code text null,
  plus_code_short text null,
  lat double precision null,
  lon double precision null,
  timezone text null,
  timezone_offset text null,
  timezone_abbreviation text null,
  geocode_id text null,
  category text null,
  county text null,
  distance double precision null,
  footway text null,
  hamlet text null,
  name text null,
  old_name text null,
  ref text null,
  state_code text null,
  suburb text null,
  town text null,
  village text null,
  fts_address_line1 tsvector GENERATED ALWAYS as (
    to_tsvector(
      'english'::regconfig,
      COALESCE(address_line1, ''::text)
    )
  ) STORED null,
  constraint addresses_pkey primary key (id),
  constraint addresses_place_id_key unique (place_id)
) TABLESPACE pg_default;


create table public.parcel_addresses (
  id bigserial not null,
  parcel_id bigint not null,
  address_id bigint not null,
  effective_date date not null default CURRENT_DATE,
  end_date date null,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid (),
  constraint parcel_addresses_pkey primary key (id),
  constraint parcel_addresses_address_id_fkey foreign KEY (address_id) references addresses (id) on delete CASCADE,
  constraint parcel_addresses_parcel_id_fkey foreign KEY (parcel_id) references parcels (id) on delete CASCADE,
  constraint parcel_addresses_date_chk check (
    (
      (end_date is null)
      or (end_date > effective_date)
    )
  )
) TABLESPACE pg_default;


create table public.parcel_neighborhoods (
  id bigserial not null,
  parcel_id bigint not null,
  neighborhood_id integer not null,
  effective_date date not null,
  end_date date null,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid (),
  constraint parcel_neighborhoods_pkey primary key (id),
  constraint parcel_neighborhoods_neighborhood_id_fkey foreign KEY (neighborhood_id) references neighborhoods (id) on delete CASCADE,
  constraint parcel_neighborhoods_parcel_id_fkey foreign KEY (parcel_id) references parcels (id) on delete CASCADE,
  constraint parcel_neighborhoods_date_chk check (
    (
      (end_date is null)
      or (end_date > effective_date)
    )
  )
) TABLESPACE pg_default;


create table public.neighborhoods (
  neighborhood integer generated by default as identity not null,
  "group" integer null,
  polygon jsonb[] null,
  set_id bigint null,
  name text null,
  id bigserial not null,
  constraint neighborhoods_pkey primary key (id),
  constraint neighborhoods_id_key unique (id),
  constraint neighborhoods_set_id_fkey foreign KEY (set_id) references neighborhood_sets (id)
) TABLESPACE pg_default;


create table public.neighborhood_sets (
  id bigserial not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  retired_at timestamp with time zone null,
  created_by uuid not null default auth.uid (),
  constraint neighborhood_sets_pkey primary key (id)
) TABLESPACE pg_default;



create table public.parcel_value_sets (
  id bigint generated by default as identity not null,
  parcel_id bigint not null,
  tax_year integer not null,
  approach text not null,
  review_id bigint not null,
  totals jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  supersedes_value_set_id bigint null,
  constraint parcel_value_sets_pkey primary key (id),
  constraint parcel_value_sets_review_id_fkey foreign KEY (review_id) references reviews (id) on delete RESTRICT,
  constraint parcel_value_sets_supersedes_value_set_id_fkey foreign KEY (supersedes_value_set_id) references parcel_value_sets (id)
) TABLESPACE pg_default;


create table public.parcel_value_set_snapshots (
  id bigint generated by default as identity not null,
  value_set_id bigint not null,
  review_id bigint not null,
  residential_land_value numeric null,
  commercial_land_value numeric null,
  agricultural_land_value numeric null,
  total_land_value numeric not null,
  residential_improvement_value numeric null,
  commercial_improvement_value numeric null,
  agricultural_improvement_value numeric null,
  total_improvement_value numeric not null,
  total_value numeric not null,
  created_at timestamp with time zone not null default now(),
  effective_at date not null default CURRENT_DATE,
  constraint parcel_value_set_snapshots_pkey primary key (id),
  constraint parcel_value_set_snapshots_review_id_fkey foreign KEY (review_id) references reviews (id) on delete RESTRICT,
  constraint parcel_value_set_snapshots_value_set_id_fkey foreign KEY (value_set_id) references parcel_value_sets (id) on delete CASCADE
) TABLESPACE pg_default;


create table public.structure_snapshots (
  id bigint generated by default as identity not null,
  structure_id bigint not null,
  review_id bigint null,
  best_use_id bigint null,
  condition_id bigint null,
  created_by uuid not null default auth.uid (),
  created_at timestamp with time zone not null default now(),
  effective_at date not null default CURRENT_DATE,
  total_area_sqft integer null,
  total_livable_sqft integer null,
  number_of_units integer null,
  number_of_bedrooms integer null,
  number_of_bathrooms numeric null,
  number_of_stories integer null,
  brick_sqft integer null,
  frame_sqft integer null,
  concrete_sqft integer null,
  attached_garage_sqft integer null,
  attic_livable_sqft integer null,
  attic_unfinished_sqft integer null,
  basement_finished_sqft integer null,
  basement_unfinished_sqft integer null,
  replacement_cost_new numeric null,
  sections_detail jsonb not null default '{}'::jsonb,
  year_built integer null,
  base_material_id bigint null,
  category text null,
  constraint structure_snapshots_pkey primary key (id),
  constraint structure_snapshots_base_material_id_fkey foreign KEY (base_material_id) references construction_materials (id) on delete set null,
  constraint structure_snapshots_best_use_id_fkey foreign KEY (best_use_id) references structure_uses (id) on delete set null,
  constraint structure_snapshots_condition_id_fkey foreign KEY (condition_id) references structure_conditions (id) on delete set null,
  constraint structure_snapshots_review_id_fkey foreign KEY (review_id) references reviews (id) on delete set null
) TABLESPACE pg_default;


create table public.structure_parcel_links (
  id bigint generated by default as identity not null,
  structure_id bigint not null,
  parcel_id bigint not null,
  review_id bigint null,
  effective_at date not null default CURRENT_DATE,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid (),
  constraint structure_parcel_links_pkey primary key (id),
  constraint structure_parcel_links_review_id_fkey foreign KEY (review_id) references reviews (id) on delete set null
) TABLESPACE pg_default;

create table public.property_classes (
  id integer generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  constraint property_classes_pkey primary key (id)
) TABLESPACE pg_default;


create table public.parcel_property_classes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  parcel_id bigint null,
  start_date date not null,
  end_date date null,
  property_class_id integer null,
  constraint parcel_preoperty_classes_pkey primary key (id),
  constraint parcel_preoperty_classes_parcel_id_fkey foreign KEY (parcel_id) references test_parcels (id),
  constraint parcel_property_classes_property_class_id_fkey foreign KEY (property_class_id) references property_classes (id)
) TABLESPACE pg_default;